<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tiendaelchino</title>
</head>
 <body>
        <div class="" id="">
          <h1> <span class = " tittles-pages-logo " >Tienda de electronicos el chino </span > 
            <p>
               Bienvenido a nuestra,aquí encontrará una gran variedad de artículos.
            </p>
          </h1>
        </div>
        <section  id="">
            <div class="container">
                <div class="page-header">

                  <h1> Novedades <pequeño> productos </pequeño> </h1 >
                </div>



            </div>


        </section>

    
 </body>
</html>